<?php
namespace app\common\base;
use yii\base\Module;

/**
 * Class BaseModule
 * @package app\common\base
 */
class BaseModule extends Module
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $file = $this->getBasePath().'/config/config.php';
        if(file_exists($file)){
            \Yii::configure($this, require($file));
        }
    }
}